title: Zenith
email: jinlai.xu@pitt.edu
description: A fork of @orderlist's Minimal theme, built for GitHub Pages + Jekyll

# HEADS UP: Change these for your use
baseurl: "/Zenith/" 
url: "https://bpln.github.io/Zenith/"


# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - /tmp/
  - config.ru


# Development Parameter for Puma 
destination: "public/minimal-jekyll-ghp"
