# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Zenith
tagline:          'Zenith'
description:      'An Edge Federation'
url:              https://bpln.github.io/Zenith
baseurl:          "/Zenith" # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Jinlai Xu'
  url:            https://jinlaixu.net

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  false
github:
  repo:             https://github.com/xujinlai
